### ISSUE TITLE
(feat) Implement the Context API as a global state solution.

### ISSUE THREAD

**Issue by jaxcksn** [ttugdsc/raiderride-FUBU#5]
**Is your feature request related to a problem? Please describe.**
Because of the way React Navigation works, we need a way to manage global state as we can't easily pass props to navigation screens.

**Describe the solution you'd like**
I would like to implement a global state using the [React Native Context API](https://reactjs.org/docs/context.html). This could store things like the authentication state and the global user data.

**Describe alternatives you've considered**
Redux is an alternative, but would increase complexity by a large amount.

**Additional context**
This would adapt as the backend is created, but having it ready before the backend means we can develop the front end with a default state and just add code to the change the state instead of changing every past component we've made.

**Comment by Guysnacho** [comment]
My knee-jerk reaction was why not use Redux Toolkit since it works with react native but you're right. Even with the added help rtk brings the context api is a lot simpler. [Example](https://reactjs.org/docs/context.html#classcontexttype) - This
```JavaScript
class MyClass extends React.Component {
  static contextType = MyContext;
  render() {
    let value = this.context;
    /* render something based on the value */
  }
}
```
is gonna save us from a million headaches so go for it.
